ALTER TABLE "Company" ADD COLUMN "startDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Company" ADD COLUMN "endDate" TIMESTAMP(3);

ALTER TABLE "User" ADD COLUMN "endDate" TIMESTAMP(3);

ALTER TABLE "Client" ADD COLUMN "startDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Client" ADD COLUMN "endDate" TIMESTAMP(3);

ALTER TABLE "Project" ADD COLUMN "clientId" TEXT;
ALTER TABLE "Project" ADD COLUMN "startDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Project" ADD COLUMN "endDate" TIMESTAMP(3);

ALTER TABLE "Project" ADD CONSTRAINT "Project_clientId_fkey" FOREIGN KEY ("clientId") REFERENCES "Client"("id") ON DELETE SET NULL ON UPDATE CASCADE;
